# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78d55842ac7b6cbb60072749da2e767a50d0e9ae6e84730822be10649c72fee1708b173c15ed8248f03a8b824d63bee4d16543eec6e19af55bc13b37fdd4f5cf

test:
  secret_key_base: 2ceadbc84522bb718e3cb4b134697ca98d33ad77a72ad444aea16cf4f5563c33e870b53cf60558288cb328a96f9699067e352f4d4aa32c26644ccbc268b47272

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
